### ISSUE TITLE
NameError: name 'corrupt_msg' is not defined

### ISSUE THREAD

**Issue by deepak-kumar-98** [mendez-luisjose/license_detection#1]
Using CPU. Note: This module is much faster with a GPU.
2024-02-22 00:43:08.444 Uncaught app exception
Traceback (most recent call last):
  File "/home/hs/License-Plate-Detection-with-YoloV8-and-EasyOCR/myenv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/home/hs/License-Plate-Detection-with-YoloV8-and-EasyOCR/app.py", line 8, in <module>
    from util import set_background, write_csv
  File "/home/hs/License-Plate-Detection-with-YoloV8-and-EasyOCR/util.py", line 29, in <module>
    reader = easyocr.Reader(['en'], gpu=False)
  File "/home/hs/License-Plate-Detection-with-YoloV8-and-EasyOCR/myenv/lib/python3.10/site-packages/easyocr/easyocr.py", line 184, in __init__
    LOGGER.warning(corrupt_msg)
NameError: name 'corrupt_msg' is not defined

I am getting above error, kindly help me out

**Comment by 3nK1i** [comment]
Hi @deepak-kumar-98,

I investigated this error and found the root cause. Here's what's happening and how to fix it in the meantime :

## Root Cause
"util.py" initializes "easyocr.Reader" at **module level** (line 29), which means  it runs the moment "util.py" is imported by "app.py". This conflicts with certain versions of EasyOCR where "corrupt_msg" is referenced before assignment inside EasyOCR's own "__init__", surfacing as the "NameError" you see.

On top of that, "easyocr.Reader" is already initialized in "app.py" line 12, so "util.py" is doing it twice, causing a double load on startup that triggers the bug.

## Temporary Fix (works right now)
Remove or comment out line 29 in "util.py" :
```python
# DELETE or comment this line in util.py :
reader = easyocr.Reader(['en'], gpu=False)
```
The reader is already correctly initialized in "app.py", so removing it from "util.py" is safe and actually the correct architecture.
Also pin a stable EasyOCR version in your environment :
```bash
pip install easyocr==1.7.1
```
## Permanent Fix
I'm currently working on a PR that fixes this properly along with several other silent bugs I found during a full code review. It will be linked to this issue once submitted.

Hope this helps !
